apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-deployment
  namespace: dev
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app-container
          image: hiteshchavhan811/test-app:latest
          ports:
            - containerPort: 8090
          env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: password
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: database_url

---
apiVersion: v1
kind: Service
metadata:
  name: test-app-service
spec:
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090